version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - ./gradlew clean
  build:
    commands:
      - echo Build started
      - java -version
      - ./gradlew buildArtifact
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - _dist/*.jar
    - _dist/.ebextensions/**/*
    - _dist/Procfile
#  base-directory: '_dist'
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'