version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - ./gradlew clean
  build:
    commands:
      - echo Build started
      - java -version
      - ./gradlew buildNonZipArtifact
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
#    - _dist/*.jar
#    - _dist/.ebextensions/**/*
#    - _dist/Procfile
     - '**/*'
  base-directory: '_dist'
  discard-paths: no # In case of Yes, all the file in subDirectory(e.g., .ebextensions) will be located directly under root
  name: Aritifact-Zip-$(date +%Y-%m-%d)
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'